// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://wyovmwbtniqcomqpppkk.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5b3Ztd2J0bmlxY29tcXBwcGtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMTAxODIsImV4cCI6MjA2ODc4NjE4Mn0.q9AAUvmZ6C6LqndTrxKUifX179SXQs2TIoL9DkU7cko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});